# Generated by Django 4.0.2 on 2022-02-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, max_length=555, null=True)),
                ('dialog', models.CharField(blank=True, max_length=555, null=True)),
                ('movie', models.CharField(blank=True, max_length=555, null=True)),
                ('character_id', models.CharField(blank=True, max_length=555, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(blank=True, max_length=555, null=True)),
                ('height', models.CharField(blank=True, max_length=555, null=True)),
                ('race', models.CharField(blank=True, max_length=555, null=True)),
                ('gender', models.CharField(blank=True, max_length=555, null=True)),
                ('birth', models.CharField(blank=True, max_length=555, null=True)),
                ('spouse', models.CharField(blank=True, max_length=555, null=True)),
                ('death', models.CharField(blank=True, max_length=555, null=True)),
                ('realm', models.CharField(blank=True, max_length=555, null=True)),
                ('hair', models.CharField(blank=True, max_length=555, null=True)),
                ('name', models.CharField(blank=True, max_length=555, null=True)),
                ('wikiUrl', models.CharField(blank=True, max_length=555, null=True)),
                ('qoutes', models.ManyToManyField(related_name='character_qoutes', to='one_api.UserFavouriteQuote')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
