# Generated by Django 4.0.2 on 2022-02-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoritecharacter',
            old_name='qoutes',
            new_name='quotes',
        ),
    ]
